# Generated by Django 3.1.1 on 2020-10-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_register', '0009_contest_unofficial_ranking_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announce_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
    ]
