# Generated by Django 3.1.1 on 2021-08-06 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_register', '0011_auto_20210526_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='contest_name',
        ),
        migrations.AddField(
            model_name='contest',
            name='cms_name',
            field=models.CharField(default='TODO cms_name', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contest',
            name='public_name',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cms_name', models.CharField(max_length=100)),
                ('public_name', models.CharField(blank=True, max_length=200)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_register.contest')),
            ],
        ),
    ]
