# Generated by Django 3.1.1 on 2021-08-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_register', '0012_auto_20210806_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='contest_url',
        ),
        migrations.AddField(
            model_name='contest',
            name='practice_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contest',
            name='cms_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
