# Generated by Django 3.1.1 on 2021-08-06 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_register', '0013_auto_20210806_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='unofficial_ranking_file',
        ),
    ]
