# Generated by Django 3.1.1 on 2021-08-06 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_register', '0014_remove_contest_unofficial_ranking_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
