# Generated by Django 3.1.1 on 2021-08-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_register', '0015_delete_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='participants_count',
            field=models.IntegerField(default=0),
        ),
    ]
